name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug - List files in the workspace
        run: ls -R  # This will print all files and folders to check where `manage.py` is

      - name: Run Django tests
        run: |
          if [ -f "manage.py" ]; then
            python manage.py test
          elif [ -d "Automation-RoboticsScripts" ] && [ -f "Automation-RoboticsScripts/manage.py" ]; then
            cd Automation-RoboticsScripts
            python manage.py test
          else
            echo "Error: manage.py not found!" && exit 1
          fi
